add: SECUTIRY.md
SuteraVR/.github pull request #14
Opened 2024-03-29 09:38 UTC by See2et

- close #2

2024-03-29 09:54 UTC, tukiminya requested changes
Publicなところにそもそも公開しないように明確化してほしい！

2024-03-29 10:05 UTC, haruki7049 commented
> Publicなところにそもそも公開しないように明確化してほしい！

Publicなところってどこを指してたりします？

2024-03-29 10:24 UTC, tukiminya commented
> > Publicなところにそもそも公開しないように明確化してほしい！
> 
> Publicなところってどこを指してたりします？

GitHub Issueだったり、各種SNSだったりですね

2024-03-29 10:28 UTC, haruki7049 commented
理解した。要は他のプラットフォームに公開しないでねって事を書いてほしいってことやな。

2024-04-04 07:28 UTC, tukiminya commented
@See2et 空いているときに対応お願いしますー！

2024-04-04 07:29 UTC, See2et commented
ほいほい

2024-04-04 11:35 UTC, See2et commented
@tukiminya こんな感じかな？

2024-04-04 14:50 UTC, tukiminya requested changes

2024-04-04 14:50 UTC, tukiminya commented on SECURITY.md
> +**Do not** report security issues on any public spaces: Github Issue, Twitter, etc.
私は許せないけど、一応公式がXと言っているので。
それ以外は大丈夫です！
```suggestion
**Do not** report security issues on any public spaces: Github Issue, X(Twitter), etc.
```

2024-04-04 14:52 UTC, tukiminya approved these changes

2024-04-04 14:52 UTC, tukiminya commented
Request Review @haruki7049

2024-04-09 02:27 UTC, haruki7049 approved these changes
Sorry for the delay. LGTM!!

2024-04-14 05:24 UTC, merged