Create CONTRIBUTING.md
SuteraVR/.github pull request #7
Opened 2023-12-05 00:31 UTC by haruki7049

2023-12-05 05:30 UTC, AsPulse requested changes
あとは全体的に、`<br>` の代わりに 一行空行とか`  `(半角スペースx2)を使った方がMarkdownらしいかなとは思います！

2023-12-05 05:30 UTC, AsPulse commented on CONTRIBUTING.md
> +This guide was written for Japanese-speaking contributors. If you are an English speaker and would like to contribute, please post to [GitHub Discussion in SuteraVR](https://github.com/SuteraVR/Suter
```suggestion
This guide was written for Japanese-speaking contributors. If you are an English speaker and would like to contribute, please post on [GitHub Discussion in SuteraVR](https://github.com/SuteraVR/SuteraVR/discussions).<br>
```

2023-12-05 05:30 UTC, AsPulse commented on CONTRIBUTING.md
> +`#{イシューの番号}-{実装内容を簡潔に、かつハイフンで区切って記す}`のように作成してください。
ブランチ名……個人的には制約なしで良い派
Squash and mergeするなら、PR名 (`main`のコミットメッセージ)  とかを [Conventional commit](https://www.conventionalcommits.org/ja/v1.0.0/) なんかに従わせてもいいかも

命名規則を作るにしても、`[0-9][A-z][.-_/]` 以外はエスケープ必須なので、ダメではないんだけど`#`は避けたほうが無難かなと思います

2023-12-05 05:53 UTC, haruki7049 commented on CONTRIBUTING.md
> +`#{イシューの番号}-{実装内容を簡潔に、かつハイフンで区切って記す}`のように作成してください。
実はDiscord上で話が決まってしまっていたり。`#`をブランチ名に入れると面倒だなぁと後から感じてきたという話。

2023-12-05 11:02 UTC, haruki7049 commented on CONTRIBUTING.md
> +This guide was written for Japanese-speaking contributors. If you are an English speaker and would like to contribute, please post to [GitHub Discussion in SuteraVR](https://github.com/SuteraVR/Suter
https://github.com/SuteraVR/.github/pull/7/commits/1979f3063e19902e26b127a30680e806dd4ef864

2023-12-18 13:02 UTC, AsPulse requested changes
第四回定例の内容

### ブランチ名
ブランチ名: conventionalなキーワード + スラッシュ + 簡単な説明！
例: `chore/hogehoge-foobar`

### close keyword
- PR名に`- close #35`なのつける
- 二つログでちゃう問題あるからCreate Branchは禁止



### そのほか

- PRはProjectにいれない
- Merge方法規則は省略 (強制されているので)

2023-12-19 09:12 UTC, AsPulse approved these changes

2023-12-19 09:12 UTC, AsPulse commented on CONTRIBUTING.md
> +```
```suggestion
### CI/CDの追加

現在存在するCIは、
cargo test, rustfmt, clippyをそれぞれのRustクレートに対して走らせるもののみです。
```

ちょっとこれ無意味すぎるな...
ワークフローを並べるだけなら、正直`.github/workflows`見ればわかることだし
説明をちゃんとする or 節ごと削除かなぁ……

2023-12-19 09:12 UTC, AsPulse commented on CONTRIBUTING.md
> +- イシューの命名規則は、[Conventional Commits:v1.0.0](https://www.conventionalcommits.org/ja/v1.0.0/)に従ってください。
```suggestion
- イシューは、[Conventional Commits:v1.0.0](https://www.conventionalcommits.org/ja/v1.0.0/)のタイトルと同じように名前を付けてください。
```
Conventional Commitsは、あくまでコミットメッセージの書き方を述べるものだからこうした方がいいかな……

2023-12-19 09:13 UTC, AsPulse requested changes
(間違えてApproveしちゃった)

2023-12-19 10:10 UTC, haruki7049 commented on CONTRIBUTING.md
> +```
https://github.com/SuteraVR/.github/pull/7/commits/15a45999f3370341c5dc32a6445c75e0614b4ea7

2023-12-19 10:12 UTC, AsPulse approved these changes
LGTM!

2023-12-19 10:14 UTC, merged